# Generated by Django 2.2 on 2020-05-07 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProCot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.MainCot')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='demo.jpg', upload_to='productImg')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(default=datetime.datetime.today)),
                ('ability', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='-')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProCot')),
            ],
        ),
    ]
